name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Runs when code is pushed to 'main'

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image to Docker Hub
      run: |
        docker buildx build --file ./Dockerfile --tag 20059516/my-web-app:${{ github.sha }} --push .

  Deploy-To-VM:
    needs: Build-and-Push
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Docker Container on Azure VM
      run: |
        # SSH into your VM (replace with your private key and VM IP)
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} azureuser@40.82.207.123 << 'EOF'
        
        # Ensure Docker is installed
        sudo apt update && sudo apt install -y docker.io

        # Stop and remove any existing container
        docker stop my-web-app || true
        docker rm my-web-app || true

        # Pull the latest Docker image from Docker Hub
        docker pull 20059516/my-web-app:${{ github.sha }}

        # Run the Docker container
        docker run -d -p 80:80 --name my-web-app 20059516/my-web-app:${{ github.sha }}

        EOF
